### ISSUE TITLE
Its not Swift 3 compatible

### ISSUE THREAD

**Issue by rcfrias** [Swinject/SwinjectSimpleExample#5]
Just tried with Xcode 8 and the Swfit 3 conversion, and it fails to compile.

**Comment by yoichitgy** [comment]
Swift 3 migration has just merged:
https://github.com/Swinject/SwinjectSimpleExample/pull/4

Try the latest version in `master` branch again, please? CocoaPods v1.1.x is required.

**Comment by rcfrias** [comment]
Cool!, that compiled flawless. But no table-results, I guess I must go on with the instructions.

**Comment by rcfrias** [comment]
Yes, that was It, as soon as I added the key, I got the results. Thkx for the prompt response.

**Comment by yoichitgy** [comment]
Great to hear👍
